title: MTÜ Ausad Valimised
description: Demobkraatlikud valimised on vabad, tulemuste kujunemine aus ning vaadeldav, kuid valija hääl jääb tema enda teada.
theme: just-the-docs

url: https://ausadvalimised.ee

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
