title: Ausad Valimised
description: Demokraatlikud valimised on vabad, tulemuste kujunemine aus ning vaadeldav — kuid valija hääl jääb ainult tema enda teada. Valimised peavad olema ausad ja pettused välistatud.
publisher: Ausad Valimised
theme: just-the-docs

url: https://ausadvalimised.ee

logo: "/logo.svg"
favicon_ico: "/logo.svg"

#lang: et
#locale: et_EE

languages: ["et", "en"]
default_lang: "et"
exclude_from_localization: ["javascript", "media", "css", "public", "sitemap.xml"]
lang_from_path: true

#aux_links:
#  Lähtekood: https://github.com/ausadvalimised/ausadvalimised.ee

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot

sass:
    sourcemap: never

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    posts:
      name: site_news
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    docs:
      name: site_docs
      nav_exclude: false
      nav_fold: false
      search_exclude: false

defaults:
  - scope:
      path: ""
    values:
      author: Ausad Valimised
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: docs
    values:
      layout: default
